### ISSUE TITLE
Fern Rock Transportation Center misspelled on Warminster Line Outbound 

### ISSUE THREAD

**Issue by ghost** [patmaiden/septa-ninja#10]
Fern Rock displayed as:

FERN ROCK TTRANSPORTATION CTR.

Should be:

FERN ROCK TRANSPORTATION CTR.

**Comment by patmaiden** [comment]
Fixed this and one other copy issue in with commit [7d9502d](https://github.com/patmaiden/septa-ninja/commit/7d9502d6310a8aa52778c1cab5315ff3e0f4604e)
