### ISSUE TITLE
Normal conditions shouldn't have a "tweet this problem" link

### ISSUE THREAD

**Issue by ghost** [patmaiden/septa-ninja#11]
If conditions are "normal" there's really no "problem" to report to SEPTA.

If anything this could be a "Tweet this condition" or "Tweet this status"

**Comment by patmaiden** [comment]
Fixed w/ commit [fa1d9e4](https://github.com/patmaiden/septa-ninja/commit/fa1d9e4a5b12f7e0bab9e8a96b7d8dee4089281b). Decided not to show the Tweet option at all for normal conditons.
