### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by patmaiden** [patmaiden/septa-ninja#4]
Write personas (+ document them) to help guide future development beyond the port from MBTA-> SEPTA. We have been just adding features as we think of them but it would be good to have an overall vision for what SEPTA Ninja will be going forward.

**Comment by patmaiden** [comment]
Google doc for Personas: 

https://docs.google.com/document/d/1ibpjIHODPwdCCPNbOb-rWn_UVdUHYC5mQKQyRvM6zPE/edit

**Comment by early-bird-software** [comment]
We created and organized the personas.
