### ISSUE TITLE
Tweeting to SEPTA and PATCO

### ISSUE THREAD

**Issue by ppierdo** [patmaiden/septa-ninja#7]
The link to tweet a problem to SEPTA is great, but there needs to be a separate link for the PATCO line to tweet to PATCO because it's a separate system.

**Comment by ghost** [comment]
PATCO is @RidePATCO

**Comment by early-bird-software** [comment]
It would be cool if this was smart and knew when you were reporting a patco or septa issue and set up the correct tweet. 

Right now everything tweets to septa.
